### ISSUE TITLE
commit action stops without any explanation

### ISSUE THREAD

**Issue by peterkelley519** [JAndrassy/org.eclipse.team.cvs#3]
Greetings! I'm on a team that is currently using eclipse with a CVS repository.
We've found that the plugin seems to be functioning as expected except for the commit action.
The commit action seems to just fail, but with no message, no indication of what went wrong. The menu we expect to show that lets us enter commit messages and select artifacts never appears. 
We're using a workaround (committing manually outside of Eclipse) but hope it can be fixed.
I hope someone can address this. 
And in the meantime, even if someone doesn't have the time to address it - could you help us out and give us some guidance on how to get up to speed on development, particularly with this project. We don't have experience with developing Eclipse plugins but some of us would like to learn. 
Best regards!

**Comment by JAndrassy** [comment]
it looks like you have the original version by Eclipse team, which is not compatible with Eclipse 2023.
it is exactly the error fixed in this repository and published here
```
https://storage.googleapis.com/eclipse-cvs-plugin/
```
if the repo looks empty, uncheck "Group items by category"
